apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-generator
  template:
    metadata:
      labels:
        app: log-generator
    spec:
      containers:
      - name: log-generator
        image: 320819923295.dkr.ecr.us-east-1.amazonaws.com/log-backend:latest
        command: [ "python", "-m", "app.log_generator" ]