name: CI-CD pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
      
      - name: Login to ECR
        run: |
          aws ecr get-login-password | docker login --username AWS --password-stdin 554074174392.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Backend Image
        run: |
          docker build -t backend -f backend/Dockerfile ./backend
          docker tag backend:latest 554074174392.dkr.ecr.us-east-1.amazonaws.com/backend:latest

      - name: Push Backend
        run: docker push 554074174392.dkr.ecr.us-east-1.amazonaws.com/backend:latest

      - name: Build Worker Image
        run: |
          docker build -t backend -f worker/Dockerfile ./worker
          docker tag worker:latest 554074174392.dkr.ecr.us-east-1.amazonaws.com/worker:latest

      - name: Push Worker
        run: docker push 554074174392.dkr.ecr.us-east-1.amazonaws.com/worker:latest

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.0'

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/